# Generated by Django 4.2.24 on 2025-10-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviepetition_alter_movie_id_alter_movie_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetitionVote',
        ),
        migrations.DeleteModel(
            name='MoviePetition',
        ),
    ]
